import { useState } from 'react'
import { useForm } from 'react-hook-form'
import Link from 'next/link'
import { useRouter } from 'next/router'

import { signInWithEmailAndPassword } from 'firebase/auth'
import { auth } from '@/firebase.config'

import { useDispatch } from 'react-redux'
import { setUser } from '@/redux/slices/userSlice'

import { FormTypes } from './formTypes'
import styles from './Form.module.scss'
import { ExclamationCircleIcon } from '@heroicons/react/24/outline'
import Head from 'next/head'

const SignIn: React.FC = () => {
	const [email, setEmail] = useState<string>('')
	const [password, setPassword] = useState<string>('')

	const dispatch = useDispatch()
	const router = useRouter()

	const {
		register,
		formState: { errors, isValid },
		handleSubmit,
		reset,
	} = useForm<FormTypes>({
		mode: 'onBlur',
	})

	// const onSubmit = (data: FormTypes) => {
	// 	alert(JSON.stringify(data))
	// 	reset()
	// }

	const handleLogin = async (e: any) => {
		e.preventDefault()
		try {
			const userCredential = await signInWithEmailAndPassword(
				auth,
				email,
				password
			)
			const user = userCredential.user
			console.log(user)
			dispatch(
				setUser({
					email: user.email,
					id: user.uid,
					token: user.refreshToken,
				})
			)
			router.push('/')
		} catch (error) {
			console.log(error)
		}
	}

	return (
		<>
			<Head>
				<title>Cars / Login</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.body}>
				<h2>Login</h2>
				<form className={styles.form}>
					<div className={styles.input}>
						<label>
							Email Address
							<input
								{...register('email', {
									required: 'Email is a required field',
									pattern: {
										value:
											/^((([0-9A-Za-z]{1}[-0-9A-z.]{1,}[0-9A-Za-z]{1})|([0-9А-Яа-я]{1}[-0-9А-я.]{1,}[0-9А-Яа-я]{1}))@([-A-Za-z]{1,}.){1,2}[-A-Za-z]{2,})$/u,
										message: 'Please enter a valid email address',
									},
								})}
								type='email'
								value={email}
								onChange={e => setEmail(e.target.value)}
							/>
						</label>
						<div className={styles.error}>
							{errors?.email?.message && (
								<ExclamationCircleIcon className={styles.error__icon} />
							)}
							{errors?.email?.message}
						</div>
					</div>
					<div className={styles.input}>
						<label>
							Password
							<input
								{...register('password', {
									required: 'Password is a required field',
									minLength: {
										value: 8,
										message: 'Enter a minimum of 8 characters.',
									},
								})}
								type='password'
								value={password}
								onChange={e => setPassword(e.target.value)}
							/>
						</label>
						<div className={styles.error}>
							{errors?.password && errors?.password?.message && (
								<ExclamationCircleIcon className={styles.error__icon} />
							)}
							{errors?.password && errors?.password?.message}
						</div>
					</div>
					<div className={styles.item}>
						<label>
							<input type='checkbox' />
							Remember me
						</label>
						<h3>Forgot your password?</h3>
					</div>
					<h3 className={styles.link}>
						Not registered? <Link href='/SignUpPage'>Create an account</Link>
					</h3>
					<input
						type='submit'
						value='Sign in'
						disabled={!isValid}
						style={
							!isValid
								? { backgroundColor: '#909eeb' }
								: { backgroundColor: '#403ec0' }
						}
						onClick={handleLogin}
					/>
				</form>
			</div>
		</>
	)
}

export default SignIn
