import SavedCars from '@/components/SavedCars'
import Sort from '@/components/UI/select/Sort'
import {
	Items,
	selectItemsSlice,
	setSavedItems,
} from '@/redux/slices/itemsSlice'
import { selectSearchSlice } from '@/redux/slices/searchSlice'
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'

const Saved = () => {
	const { savedItems } = useSelector(selectItemsSlice)
	const { sort } = useSelector(selectSearchSlice)
	const dispatch = useDispatch()

	useEffect(() => {
		const sortById = sort.replace('-', '')
		const order = sort.includes('-') ? 'asc' : 'desc'

		axios
			.get(`http://localhost:3001/savedItems?_sort=${sortById}&_order=${order}`)

			.then(res => {
				dispatch(setSavedItems(res.data))
			})
	}, [sort])

	return (
		<>
			<Head>
				<title>Cars / Saved</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='saved'>
				<h1 className='saved__title'>Saved cars</h1>
				{savedItems.length ? (
					<div className='saved__content content'>
						<div className='saved__actions actions'>
							<div className='actions__title'>Listed cars</div>
							<div className='actions__select'>
								<Sort />
							</div>
						</div>
						<div className='saved__car'>
							{savedItems.map((item: Items) => (
								<SavedCars key={item.id} {...item} />
							))}
						</div>
					</div>
				) : (
					<div className='saved__empty saved-empty'>
						<div className='saved-empty__content'>
							<div className='saved-empty__text'>
								You have not saved a car yet((
							</div>
							<Link href='/Items' className='saved-empty__btn'>
								Shop for cars
							</Link>
						</div>
						<div className='saved-empty__img'>
							<Image
								src='/savedEmpty.jpg'
								alt='image'
								width={600}
								height={300}
							/>
						</div>
					</div>
				)}
			</div>
		</>
	)
}

export default Saved
